[package]
name = "redis-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = { version = "0.23", features = ["aio", "tokio-comp"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
# redis_cluster_async = "0.5.0" 
tokio = { version = "1.0", features = ["full"] }

